#!/bin/bash

# -----------------------------nginx----------------------------
nginx_start() {
    kubectl run my-nginx --image=nginx --replicas=2 --port=80
    kubectl expose deployment my-nginx --port=80 --type=NodePort
}

nginx_show() {
    kubectl describe services my-nginx
}

nginx_delete() {
    kubectl delete services,deployment my-nginx
}

# -----------------------------kubectl----------------------------
show_all() {
    echo -e "Pods"
    kubectl get pods --all-namespaces
    echo -e "\nServices"
    kubectl get svc --all-namespaces
    echo -e "\nDeployment"
    kubectl get deploy --all-namespaces
    echo -e "\nConfigMap"
    kubectl get cm --all-namespaces
    echo -e "\nDaemonSet"
    kubectl get ds --all-namespaces
    echo -e "\nRS"
    kubectl get rs --all-namespaces
    echo -e "\nRC"
    kubectl get rc --all-namespaces
}

show_con() {
    docker ps -a --format="table{{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Command}}"
}

# -----------------------------clean----------------------------
clean() {
    docker rm -f $(docker ps -a --format={{.ID}})
    ip link set cni0 down
    ip link set flannel.1 down
    rm -rf /var/lib/cni
    rm -rf /var/lib/kubelet
    rm -rf /var/lib/etcd
    
    #brctl delbr cni0
    #brctl delbr flannel.1
}


input="${1}"

case ${input} in
    nginx_start)
        nginx_start
        ;;
    nginx_show)
        nginx_show
        ;;
    nginx_delete)
        nginx_delete
        ;;
    show_all)
        show_all
        ;;
    show_con)
        show_con
        ;;
    clean)
        clean
        ;;
    *)
        echo "usage --"
        ;;
esac
