#!/bin/bash

# -----------------------------nginx----------------------------
run_demo() {
    kubectl run k8s-demo --image=nginxdemos/hello --replicas=2 --port=80
    kubectl expose deployment k8s-demo --port=80 --type=NodePort
}

show_demo() {
    kubectl describe services k8s-demo
}

rm_demo() {
    kubectl delete services,deployment k8s-demo
}

# -----------------------------kubectl----------------------------
show_all() {
    echo -e "Pods"
    kubectl get pods --all-namespaces
    echo -e "\nServices"
    kubectl get svc --all-namespaces
    echo -e "\nDeployment"
    kubectl get deploy --all-namespaces
    echo -e "\nConfigMap"
    kubectl get cm --all-namespaces
    echo -e "\nDaemonSet"
    kubectl get ds --all-namespaces
    echo -e "\nRS"
    kubectl get rs --all-namespaces
    echo -e "\nRC"
    kubectl get rc --all-namespaces
}

show_con() {
    docker ps -a --format="table{{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Command}}"
}

# -----------------------------clean----------------------------
clean() {
    docker rm -f $(docker ps -a --format={{.ID}})
    ip link set cni0 down
    ip link set flannel.1 down
    
    cat /proc/mounts | awk '{print $2}' | grep '/var/lib/kubelet' | xargs umount
    rm -rf /var/lib/cni
    rm -rf /var/lib/kubelet
    rm -rf /var/lib/etcd
}


input="${1}"

case ${input} in
    run_demo)
        run_demo
        ;;
    show_demo)
        show_demo
        ;;
    rm_demo)
        rm_demo
        ;;
    show_all)
        show_all
        ;;
    show_con)
        show_con
        ;;
    clean)
        clean
        ;;
    *)
        echo "usage --"
        ;;
esac
