apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"DaemonSet","apiVersion":"extensions/v1beta1","metadata":{"name":"kube-flannel-ds","namespace":"kube-system","creationTimestamp":null,"labels":{"app":"flannel","tier":"node"}},"spec":{"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"flannel","tier":"node"}},"spec":{"volumes":[{"name":"run","hostPath":{"path":"/run"}},{"name":"cni","hostPath":{"path":"/etc/cni/net.d"}},{"name":"flannel-cfg","configMap":{"name":"kube-flannel-cfg"}}],"containers":[{"name":"kube-flannel","image":"k8s/flannel:v0.6.1-28-g5dde68d-amd64","command":["/opt/bin/flanneld","--ip-masq","--kube-subnet-mgr"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"resources":{},"volumeMounts":[{"name":"run","mountPath":"/run"},{"name":"flannel-cfg","mountPath":"/etc/kube-flannel/"}],"securityContext":{"privileged":true}},{"name":"install-cni","image":"k8s/flannel:v0.6.1-28-g5dde68d-amd64","command":["/bin/sh","-c","set
      -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf;
      while true; do sleep 3600; done"],"resources":{},"volumeMounts":[{"name":"cni","mountPath":"/etc/cni/net.d"},{"name":"flannel-cfg","mountPath":"/etc/kube-flannel/"}]}],"nodeSelector":{"beta.kubernetes.io/arch":"amd64"},"hostNetwork":true}}},"status":{"currentNumberScheduled":0,"numberMisscheduled":0,"desiredNumberScheduled":0,"numberReady":0}}'
  creationTimestamp: 2017-01-17T08:34:41Z
  generation: 1
  labels:
    app: flannel
    tier: node
  name: kube-flannel-ds
  namespace: kube-system
  resourceVersion: "419"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/kube-flannel-ds
  uid: ca99a347-dc8f-11e6-8b75-08002744c604
spec:
  selector:
    matchLabels:
      app: flannel
      tier: node
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flannel
        tier: node
    spec:
      containers:
      - command:
        - /opt/bin/flanneld
        - --ip-masq
        - --kube-subnet-mgr
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: k8s/flannel:v0.6.1-28-g5dde68d-amd64
        imagePullPolicy: IfNotPresent
        name: kube-flannel
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /run
          name: run
        - mountPath: /etc/kube-flannel/
          name: flannel-cfg
      - command:
        - /bin/sh
        - -c
        - set -e -x; cp -f /etc/kube-flannel/cni-conf.json /etc/cni/net.d/10-flannel.conf;
          while true; do sleep 3600; done
        image: k8s/flannel:v0.6.1-28-g5dde68d-amd64
        imagePullPolicy: IfNotPresent
        name: install-cni
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/cni/net.d
          name: cni
        - mountPath: /etc/kube-flannel/
          name: flannel-cfg
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /run
        name: run
      - hostPath:
          path: /etc/cni/net.d
        name: cni
      - configMap:
          defaultMode: 420
          name: kube-flannel-cfg
        name: flannel-cfg
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
  numberReady: 1
